"""Synthetic fed-batch run generator.


"""

from __future__ import annotations

from dataclasses import replace

import numpy as np
import pandas as pd

from cellpilot.model import FeedEvent, InitialState, ModelParams, simulate
from cellpilot.schema import CultureRun, Measurement, Variable


_NOISE: dict[Variable, float] = {
    Variable.VCD: 0.07,
    Variable.VIABILITY: 0.03,
    Variable.GLUCOSE: 0.05,
    Variable.GLUTAMINE: 0.08,
    Variable.LACTATE: 0.06,
    Variable.AMMONIA: 0.08,
    Variable.TITER: 0.05,
}


def _sample_initial(rng: np.random.Generator) -> InitialState:
    return InitialState(
        Xv=float(rng.uniform(0.2, 0.5)),
        Glc=float(rng.uniform(20.0, 40.0)),
        Gln=float(rng.uniform(4.0, 8.0)),
        Amm=float(rng.uniform(0.2, 1.0)),
        V=50.0,
    )


def _sample_feeds(rng: np.random.Generator) -> list[FeedEvent]:
    """0-3 glucose/glutamine boluses on a plausible fed-batch schedule."""
    n = int(rng.integers(0, 4))
    feeds = []
    for _ in range(n):
        feeds.append(
            FeedEvent(
                time_h=float(rng.choice([48, 72, 96, 120, 144])),
                volume_ml=float(rng.uniform(2.0, 6.0)),
                glucose_mM=float(rng.uniform(100.0, 400.0)),
                glutamine_mM=float(rng.uniform(20.0, 80.0)),
            )
        )
    return feeds


def simulate_run(
    run_id: str,
    *,
    seed: int,
    t_end: float = 240.0,
    sample_every_h: float = 24.0,
    params: ModelParams | None = None,
) -> tuple[CultureRun, pd.DataFrame]:
    """Generate one noisy, sparsely-sampled synthetic run.

    Returns the observed :class:`CultureRun` (what an instrument would log) and the
    dense ground-truth trajectory (for plotting / evaluation).
    """
    rng = np.random.default_rng(seed)
    initial = _sample_initial(rng)
    feeds = _sample_feeds(rng)
    
    
    truth_params = replace(
        params or ModelParams(),
        k_lac_uptake=float(rng.uniform(0.010, 0.025)),
        Y_x_lac=float(rng.uniform(0.4, 0.7)),
    )
    truth = simulate(initial, t_end=t_end, params=truth_params, feeds=feeds, dt=1.0)

    sample_times = np.arange(0.0, t_end + 1e-9, sample_every_h)
    measurements: list[Measurement] = []
    for t in sample_times:
        nearest = truth.index[np.argmin(np.abs(truth.index.to_numpy() - t))]
        row = truth.loc[nearest]
        for var, rel_sd in _NOISE.items():
            true_val = float(row[var.value])
            noisy = true_val * (1.0 + rng.normal(0.0, rel_sd))
            if var is Variable.VIABILITY:
                noisy = float(np.clip(noisy, 0.0, 1.0))
            measurements.append(
                Measurement(time_h=float(t), variable=var, value=max(noisy, 0.0))
            )

    run = CultureRun(
        run_id=f"SYNTH-{run_id}",
        measurements=measurements,
        cell_line="synthetic-CHO",
        notes="Generated by cellpilot.data; not real experimental data.",
    )
    return run, truth


def make_dataset(n_runs: int = 12, seed: int = 0, **kwargs) -> list[CultureRun]:
    """Generate a small dataset of synthetic runs for training/eval/demo."""
    return [simulate_run(f"{i:03d}", seed=seed + i, **kwargs)[0] for i in range(n_runs)]


def to_messy_csv(run: CultureRun) -> pd.DataFrame:
    """Render a run as a wide CSV with deliberately messy, instrument-style headers,
    to exercise the ingestion column-mapper."""
    wide = run.pivot()
    rename = {
        Variable.VCD.value: "Viable Cell Density (10^6 cells/mL)",
        Variable.VIABILITY.value: "Viability [%]",
        Variable.GLUCOSE.value: "Gluc (mM)",
        Variable.GLUTAMINE.value: "Gln (mM)",
        Variable.LACTATE.value: "Lactate (mM)",
        Variable.AMMONIA.value: "NH4+ (mM)",
        Variable.TITER.value: "mAb Titer (g/L)",
        Variable.VOLUME.value: "Working Vol (mL)",
    }
    wide = wide.rename(columns=rename)
    if "Viability [%]" in wide.columns:
        wide["Viability [%]"] = wide["Viability [%]"] * 100.0
    wide = wide.reset_index().rename(columns={"time_h": "Culture Time (h)"})
    return wide
